im=new Array;
if (document.images)
{
	im[0] = new Image()
	im[0].src = 'boss.png';
	im[1] = new Image()
	im[1].src = 'chainik.png';
	im[2] = new Image()
	im[2].src = 'charaster.png';
	im[3] = new Image()
	im[3].src = 'fairy.png';
	im[4] = new Image()
	im[4].src = 'fon.jpg';
	im[5] = new Image()
	im[5].src = 'fon_blue.jpg';
	im[6] = new Image()
	im[6].src = 'fon_boss.jpg';
	im[7] = new Image()
	im[7].src = 'fon_game_over.jpg';
	im[8] = new Image()
	im[8].src = 'fon_green.jpg';
	im[9] = new Image()
	im[9].src = 'fon_win.jpg';
	im[10] = new Image()
	im[10].src = 'fon_win.png';
	im[11] = new Image()
	im[11].src = 'game_over.png';
	im[12] = new Image()
	im[12].src = 'kuvshin.png';
	im[13] = new Image()
	im[13].src = 'live.png';
	im[14] = new Image()
	im[14].src = 'raspashonka.png';
	im[15] = new Image()
	im[15].src = 'shtany.png';
	im[16] = new Image()
	im[16].src = 'start.jpg';
	im[17] = new Image()
	im[17].src = 'start.png';
	im[18] = new Image()
	im[18].src = 'stiralka.png';
	im[19] = new Image()
	im[19].src = 'utjug.png';
	im[20] = new Image()
	im[20].src = 'win.png';
	
	im[21] = new Image()
	im[21].src = 'plan/lestnica.png';
	im[22] = new Image()
	im[22].src = 'plan/lestnicaonline.png';
	im[23] = new Image()
	im[23].src = 'plan/line.png';
	im[24] = new Image()
	im[24].src = 'plan/platform.png';
	im[25] = new Image()
	im[25].src = 'plan/pusto.png';
	im[26] = new Image()
	im[26].src = 'plan/wall.png';
}
